### ISSUE TITLE
Problem with the New CentOS / RH 7.3  ipa 4.40

### ISSUE THREAD

**Issue by gueniewie** [pdf/freeipa-user-mailalternateaddress#1]
Hello Peter,

I mean / hope it is only a Problem with the "Mask" in the new 4.4.0 Version, but I miss now the Icon for AlternatveMailAddress, but I mean I can add or remove AlternatMailAddress ?

**Comment by pdf** [comment]
The problem may be related to: https://fedorahosted.org/freeipa/ticket/5864

Unfortunately, it's not clear from the issue what the relevant changes might be, seems like some commits may be missing from the issue.

I still don't have an install of 4.4 (4.3 is still the stable release), so this may take some time for me to get tested.

**Comment by pdf** [comment]
Actually looks like a lot has changed in the way plugins are implemented, I'll have to try and work out how to migrate this.

**Comment by gueniewie** [comment]
Thanks for your work! I hope we have soon a working plugin again ;-)

Thanks

**Comment by Yamakasi** [comment]
Would be nice to see this working, I have added this to:

https://fedorahosted.org/freeipa/ticket/5521#comment:8

Maybe they pick it up for mainstream.

**Comment by pdf** [comment]
Sorry all, I know how to make this work now, but I'd hoped to find some time to use the built-in method to modify schema, and to package this up, so that I can deal with FreeIPA version dependencies for various distros.

Unfortunately, other things have demanded my attention, and since it doesn't look like I'll have the time to do this as I'd prefer, I'll make time to just perform the necessary modifications for it to work on 4.4 and add an installation prompt to select the appropriate version, or parse it from a CLI call.  I'm away this weekend though, so it likely won't be until next week some time.

**Comment by gueniewie** [comment]
Thanks, I can wait ;-)

**Comment by Yamakasi** [comment]
I'm looking forward to it, maybe the FreeIPA devs like to pick it up, I
have noticed them about it on IRC as well.

2017-02-14 12:55 GMT+01:00 gueniewie <notifications@github.com>:

**Comment by pdf** [comment]
Judging by the comments on https://fedorahosted.org/freeipa/ticket/5521 it looks like they're not particularly interested in having this functionality upstream.

Unfortunately, the plugin interfaces are not currently documented, and based on my interactions with some of the devs on the mailing, list these APIs are apparently still in flux so this may be broken again by future minor IPA releases.

**Comment by Yamakasi** [comment]
Yeah I wonder, do they manage all mail-addresses under mail= then ?
Wouldn't that be tricky ?

2017-02-14 13:09 GMT+01:00 Peter Fern <notifications@github.com>:

**Comment by pdf** [comment]
I think their reasoning is mostly that not all IPA installations will be integrated with a mail server, so for those users, the UI would be cluttered by many options that are irrelevant.  Falls under the banner of _sensible defaults_.

**Comment by gueniewie** [comment]
with my dovecot installation it is not possible, but I found Peter :-)).

**Comment by Yamakasi** [comment]
@gueniewie can you send me a mail on yamakasi.014@gmail.com ? Thanks.

**Comment by Yamakasi** [comment]
I discussed just on IRC and there had been told that all under mail= should
work, I think not as it's alphabetic ordering when you query, so we need to
keep this module alive :)

2017-02-14 13:31 GMT+01:00 gueniewie <notifications@github.com>:

**Comment by pdf** [comment]
Sorry for the delay guys, try the latest update.

**Comment by gueniewie** [comment]
Hello Peter,
Thank you for your work, I test it tomorrow morning now I go to sleep ;-).

**Comment by gueniewie** [comment]
Hello Peter,
I have a problem to install the new mailalternateaddress on my system i have this error ?
./install.sh
„./user_mailalternateaddress.js“ -> „/usr/share/ipa/ui/js/plugins/user_mailalternateaddress/user_mailalternateaddress.js“
cp: der Aufruf von stat für „./user_mailalternateaddress_4.4.py“ ist nicht möglich: Datei oder Verzeichnis not found ?
is the install.sh broken ?

Thanks for a answer.

**Comment by pdf** [comment]
Sorry, I missed committing the modified 4.4 python plugin, should be good now.

**Comment by gueniewie** [comment]
Hello Peter,

I mean something is wrong again, with the latest install.sh :-(. Now I have a other Error Messages like this ??

./install.sh
„./user_mailalternateaddress.js“ -> „/usr/share/ipa/ui/js/plugins/user_mailalternateaddress/user_mailalternateaddress.js“
„./user_mailalternateaddress_4.4.py“ -> „/usr/lib/python2.*/site-packages/ipaserver/plugins/user_mailalternateaddress.py“
cp: reguläre Datei „/usr/lib/python2.*/site-packages/ipaserver/plugins/user_mailalternateaddress.py“ kann nicht angelegt werden (can't be created): Datei oder Verzeichnis nicht gefunden (not found)

**Comment by pdf** [comment]
Hmm, that's strange - for some reason shell expansion is not working for the destination location.  I've just tested and it works fine for me here.  Please post the output of:
```bash
ls -al /usr/lib/python2.*/site-packages/ipaserver/
```
and running the installer:
```bash
bash -x ./install.sh
```

**Comment by gueniewie** [comment]
Hello Peter,
Now the output from the...
ls -al /usr/lib/python2.*/site-packages/ipaserver/
insgesamt 664
drwxr-xr-x.  5 root root  4096  4. Mär 00:10 .
drwxr-xr-x. 71 root root  8192  4. Mär 00:10 ..
drwxr-xr-x.  3 root root  4096  4. Mär 00:10 advise
-rw-r--r--.  1 root root 72477  3. Mär 01:56 dcerpc.py
-rw-r--r--.  1 root root 50525  3. Mär 04:34 dcerpc.pyc
-rw-r--r--.  1 root root 50474  3. Mär 04:34 dcerpc.pyo
-rw-r--r--.  1 root root 16960  1. Jul 2016  dns_data_management.py
-rw-r--r--.  1 root root 15265  3. Mär 04:34 dns_data_management.pyc
-rw-r--r--.  1 root root 15091  3. Mär 04:34 dns_data_management.pyo
-rw-r--r--.  1 root root   822  1. Jul 2016  __init__.py
-rw-r--r--.  2 root root   200  3. Mär 04:34 __init__.pyc
-rw-r--r--.  2 root root   200  3. Mär 04:34 __init__.pyo
drwxr-xr-x.  4 root root  8192  4. Mär 00:10 install
drwxr-xr-x.  2 root root  8192  4. Mär 00:10 plugins
-rw-r--r--.  1 root root 49321  3. Mär 01:56 rpcserver.py
-rw-r--r--.  1 root root 43412  3. Mär 04:34 rpcserver.pyc
-rw-r--r--.  1 root root 43360  3. Mär 04:34 rpcserver.pyo
-rw-r--r--.  1 root root 19712  1. Jul 2016  servroles.py                                                            
-rw-r--r--.  2 root root 21627  3. Mär 04:34 servroles.pyc
-rw-r--r--.  2 root root 21627  3. Mär 04:34 servroles.pyo
-rw-r--r--.  1 root root 49757  1. Jul 2016  session.py
-rw-r--r--.  2 root root 49079  3. Mär 04:34 session.pyc
-rw-r--r--.  2 root root 49079  3. Mär 04:34 session.pyo
-rw-r--r--.  1 root root  5477  1. Jul 2016  topology.py
-rw-r--r--.  2 root root  5735  3. Mär 04:34 topology.pyc
-rw-r--r--.  2 root root  5735  3. Mär 04:34 topology.pyo

bash -x ./install.sh
bash: ./install.sh: Datei oder Verzeichnis nicht gefunden
[root@ipa /]# 
[root@ipa freeipa-user-mailalternateaddress-master]# bash -x ./install.sh
+ set -e
+ '[' '!' -d /usr/share/ipa/ui/js ']'
+ PYSRC=user_mailalternateaddress.py
+ '[' -d /usr/lib/python2.7/site-packages/ipaserver/plugins ']'
+ PYPATH='/usr/lib/python2.*/site-packages/ipaserver/plugins'
+ PYSRC=user_mailalternateaddress_4.4.py
+ JSPATH=/usr/share/ipa/ui/js/plugins/user_mailalternateaddress
+ sudo mkdir -p /usr/share/ipa/ui/js/plugins/user_mailalternateaddress
++ dirname ./install.sh
+ sudo cp -v ./user_mailalternateaddress.js /usr/share/ipa/ui/js/plugins/user_mailalternateaddress/
„./user_mailalternateaddress.js“ -> „/usr/share/ipa/ui/js/plugins/user_mailalternateaddress/user_mailalternateaddress.js“
++ dirname ./install.sh
+ sudo cp -v ./user_mailalternateaddress_4.4.py '/usr/lib/python2.*/site-packages/ipaserver/plugins/user_mailalternateaddress.py'
„./user_mailalternateaddress_4.4.py“ -> „/usr/lib/python2.*/site-packages/ipaserver/plugins/user_mailalternateaddress.py“
cp: reguläre Datei „/usr/lib/python2.*/site-packages/ipaserver/plugins/user_mailalternateaddress.py“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden

klist
Ticket cache: KEYRING:persistent:0:0
Default principal: admin@4GJN.COM

**Comment by pdf** [comment]
I'm not sure why this is happening, but I've just pushed a change that may work around the problem for you.

**Comment by gueniewie** [comment]
Hello Peter,
I mean now it is running :-).
./install.sh
„./user_mailalternateaddress.js“ -> „/usr/share/ipa/ui/js/plugins/user_mailalternateaddress/user_mailalternateaddress.js“
„./user_mailalternateaddress_4.4.py“ -> „/usr/lib/python2.7/site-packages/ipaserver/plugins/user_mailalternateaddress.py“

Please enter your kerberos admin credentials to update FreeIPA configuration
Password for admin@4GJN.COM: 
--userobjectclasses=top --userobjectclasses=person --userobjectclasses=organizationalperson --userobjectclasses=inetorgperson --userobjectclasses=inetuser --userobjectclasses=posixaccount --userobjectclasses=krbprincipalaux --userobjectclasses=krbticketpolicyaux --userobjectclasses=ipaobject --userobjectclasses=ipasshuser --userobjectclasses=mailrecipient 

Enable aliases for existing users? [y/N] y
SASL/GSSAPI authentication started
SASL username: admin@4GJN.COM
SASL SSF: 56
SASL data security layer installed.
SASL/GSSAPI authentication started
SASL username: admin@4GJN.COM
SASL SSF: 56
SASL data security layer installed.
modifying entry "uid=admin,cn=users,cn=accounts,dc=4gjn,dc=com"
ldap_modify: Type or value exists (20)

Thanks, now I test IPA.
