### ISSUE TITLE
Problem with web Mask

### ISSUE THREAD

**Issue by gueniewie** [pdf/freeipa-user-mailalternateaddress#2]
Hello, 
I mean the Tool have a small Problem with the Mask ? I can't found the mail alias insert field for the alternate Mail address ?
CentOS 7.4 FreeIPA 4.5 I hope this is the correct version?

I hope all is working correct without this ?
Thanks for your work!
Günther

**Comment by pdf** [comment]
I'm afraid I haven't tested with 4.5 - it's possible they've changed the plugin API again, as it's not officially supported yet.  I'll try and find some time to build a test system in the near future, as my infra has rather conservative upgrade cycles for this sort of thing and won't be on 4.5 for a long time.

**Comment by Yamakasi** [comment]
Doesn't work on IPA 4.5 indeed. If you have a clue let us know!

**Comment by gueniewie** [comment]
On my system with all update, I can found it again ?

**Comment by Yamakasi** [comment]
This seems to work, I wonder why the object is modded or we can also add an extra object ?

**Comment by MrManor** [comment]
I see the same glitch in version 4.6.4. After brief testing it seems to work, but no label is shown in the UI left to Alternate mail field below Contact Setting.
